export const links = [
  [
    {
      type: "Real Estate",
      id: "col1",
      innerLink: [
        "Indian Real Estate Landscape",
        "International Real Estate Landscape",
        "Property Management",
        "Rental Market in India",
        "Land Records",
        "Govt. Portal",
        "Legal & Tax",
        "RERA",
      ],
    },
    {
      type: "Investments & Savings",
      id: "col2",
      innerLink: [
        "Home Loans",
        "GST",
        "Insurance",
        "Stocks",
        "Saving Accounts",
        "Jewels & Valuables",
        "Current Account",
        "Share Price",
        "Cibil Score",
        "Union Budget",
        "Tax",
        "Stamp Duty",
        "EPF",
        "PPF",
        "NPS",
        "FD",
      ],
    },
  ],
  [
    {
      type: "Financial Measurements",
      id: "col1",
      innerLink: [
        "Area Calculator",
        "Length Calculator",
        "Volume Calculator",
        "EMI Calculator",
        "Currency Calculator",
        "Mortgage Calculator",
        "BMI Calculator",
        "Retirement Calculator",
        "Tax Calculator",
        "Savings Calculator",
        "Lease vs. Buy Calculator",
        "Amortization Calculator",
        "Investment Calculator",
        "Time Zone Converter",
        "GPA to Percentage Calculator",
        "Body Fat Percentage Calculator",
        "Wedding Budget Calculator",
        "Inflation Calculator",
        "Home Loan Eligibility Calculator",
      ],
    },
    {
      type: "Client Corner",
      id: "col2",
      innerLink: ["Buyer Guide", "Seller Guide", "Tenant Guide", "NRI Guide"],
    },
  ],
  [
    {
      type: "Govt. Identification",
      id: "col3",
      innerLink: [
        "Aadhaar Card",
        "PAN Card",
        "Passport & VISA",
        "Voter ID Card",
        "Driving License",
        "National ID Card",
        "Ration Card",
        "Birth Certificate",
        "Marriage Certificate",
        "Employment ID Card",
        "OCI Card",
        "Caste Certificate",
        "Disability Certificate",
        "Senior Citizen Card",
        "Domicile Certificate",
        "Police Verification Certificate",
        "Disability ID Card",
        "Pension ID Card",
        "Health Insurance Card",
        "Investor ID Card",
        "Ayushman Bharat Card",
      ],
    },

    {
      type: "Reality Tech",
      id: "col5",
      innerLink: [
        "AI-Enabled Real Estate",
        "Immersive Real Estate",
        "Decentralized Real Estate",
      ],
    },
  ],
  [
    {
      type: "Lifestyle",
      id: "col4",
      innerLink: [
        "Interior & Furnishing",
        "Building Construction",
        "Smart City",
        "Smart Homes",
        "Rural Housing",
        "Vastu",
        "Celebrity Homes",
        "Govt. Infra",
        "Monuments",
        "Packers & Movers",
      ],
    },
    {
      type: "Current Trends",
      id: "col3",
      innerLink: [
        "Current Matters",
        "Hot Blogs",
        "Media Coverage",
        "Awards & Recognition",
        "Research",
        "Money Matters",
      ],
    },
    {
      type: "Startup Corner",
      id: "col4",
      innerLink: [
        "StartUp Guide",
        "Employee Guide",
        "StartUp Ideas",
        "Govt. Assistance",
      ],
    },
  ],
];
